version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: mins3nh4
      POSTGRES_DB: meubanco
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
